/**
 * IDC (Incipient Differential Calculus) log-Euler solver.
 *
 * Reference:
 *   Giannantoni, C. (2006). Mathematics for generative processes: Living and
 *   non-living systems. J. Computational and Applied Mathematics 189, 324–340.
 *   doi:10.1016/j.cam.2005.03.032
 *
 * The IDC re-reads the derivative operator "from left to right" — the future
 * state is generated by an incipient (forward) operator applied to the present
 * state.  For a positive-valued ODE  ẋ = f(x, t)  this yields (Appendix A,
 * Eq. A.4 applied numerically):
 *
 *   x_i(t+h) = x_i(t) · exp( h · f_i(x,t) / x_i(t) )
 *
 * which is the exponential (logarithmic) Euler scheme.  Key properties:
 *   1. Exact for dx/dt = ax  (pure exponential; Eq. 3.1 "persistence of form")
 *   2. Unconditionally positive — exp(·) is always strictly positive
 *   3. Produces "drift" from RK4/standard Euler for nonlinear and driven systems
 *      (the phenomenon Giannantoni analyses in §4)
 *
 * For states at or very near zero the scheme falls back to standard Euler to
 * avoid division by zero.
 */

/* ── Public types ────────────────────────────────────────────────── */

/**
 * Linear state-space descriptor  ẋ = A·x + B·u.
 * Compatible with the A/B matrices returned by the WASM SCAP bridge.
 */
export interface IdcStateSpace {
  n: number;          // state dimension
  m: number;          // input dimension
  A: number[][];      // n×n state matrix
  B: number[][];      // n×m input matrix
  u: number[];        // m constant inputs
  x0: number[];       // n initial conditions
  stateNames?: string[];
}

export interface IdcConfig {
  t_start: number;
  t_end:   number;
  dt:      number;
}

export interface IdcResult {
  solver:           'idc-log-euler';
  state_variables:  string[];
  time:             number[];
  data:             number[][];   // data[stateIdx][stepIdx]
}

/* ── Constants ───────────────────────────────────────────────────── */

/* Below this magnitude, treat state as zero and use standard Euler */
const ZERO_GUARD = 1e-100;

/* ── Core integration ────────────────────────────────────────────── */

/**
 * Compute  f = A·x + B·u  (matrix-vector products).
 */
function computeF(A: number[][], B: number[][], u: number[], x: number[]): number[] {
  const n = x.length;
  const m = u.length;
  const f: number[] = new Array(n).fill(0);
  for (let i = 0; i < n; i++) {
    let fi = 0;
    for (let j = 0; j < n; j++) fi += (A[i]?.[j] ?? 0) * x[j];
    for (let j = 0; j < m; j++) fi += (B[i]?.[j] ?? 0) * u[j];
    f[i] = fi;
  }
  return f;
}

/**
 * Single IDC log-Euler step.
 *
 * x_i(t+h) = x_i(t) · exp( h · f_i / x_i(t) )   if |x_i| > ZERO_GUARD
 *           = x_i(t) + h · f_i                     otherwise (standard Euler)
 */
function idcStep(x: number[], f: number[], h: number): number[] {
  return x.map((xi, i) => {
    const fi = f[i];
    return Math.abs(xi) < ZERO_GUARD ? xi + h * fi : xi * Math.exp(h * fi / xi);
  });
}

/* ── Public entry point ──────────────────────────────────────────── */

export function solveIDC(ss: IdcStateSpace, cfg: IdcConfig): IdcResult {
  const { n, m, A, B, u, x0 } = ss;
  const { t_start, t_end, dt } = cfg;

  const stateNames = ss.stateNames ?? Array.from({ length: n }, (_, i) => `x${i}`);

  const steps = Math.max(1, Math.round((t_end - t_start) / dt) + 1);
  const times: number[]   = [];
  const data:  number[][] = Array.from({ length: n }, () => []);

  let x: number[] = x0.slice(0, n);

  for (let s = 0; s < steps; s++) {
    const t = t_start + s * dt;
    if (t > t_end + dt * 1e-9) break;

    times.push(t);
    for (let i = 0; i < n; i++) data[i].push(x[i]);

    if (t >= t_end - dt * 1e-9) break;

    const f = computeF(A, B, u.slice(0, m), x);
    x = idcStep(x, f, dt);
  }

  return {
    solver:          'idc-log-euler',
    state_variables: stateNames,
    time:            times,
    data,
  };
}
